Feature/medios contactos
EquestriaReapers/LRT-Backend pull request #10
Opened 2023-12-07 18:27 UTC by HopeAero

Medios de Contacto implementados

Esta rama contiene el feature/migration y hotfix/user-entity

2023-12-10 11:45 UTC, Hector1567XD requested changes

2023-12-10 11:45 UTC, Hector1567XD commented on src/core/auth/dto/register.dto.ts
> +  document: string;
Ya hablamos de esto en otro PR

2023-12-10 11:45 UTC, Hector1567XD commented on src/core/auth/service/auth.service.ts
> +  async register({ email, password, name, lastname, document }: RegisterDto) {
Hablamos de esto en otro PR, pero recuerda, debe ser unico, debe ser requerido y si ya existe debe decir "nao nao, ya existe"

2023-12-10 11:45 UTC, Hector1567XD commented on src/core/profiles/dto/responses.dto.ts
> +  skills: Skill[];
El tipo `SkillData` es distinto de `Skill` especificado mas abajo, ¿por que?
```suggestion
  @ApiProperty({
    type: [SkillData],
  })
  skills: Skill[];
```

2023-12-10 11:45 UTC, Hector1567XD commented on src/core/profiles/dto/responses.dto.ts
> +import { ProfileI } from '../entities/profile.interface';
Se deberia extender o implementar algo de esta interface en este archivo? para que se importa?

2023-12-10 11:45 UTC, Hector1567XD commented on src/core/profiles/dto/responses.dto.ts
> +}
wtf o.0???? why???

2023-12-10 11:45 UTC, Hector1567XD commented on src/core/profiles/dto/responses.dto.ts
> +}
Por que volver a crear esto :S? por que no reutilizar el Entity `ContactMethod`?

2023-12-10 11:45 UTC, Hector1567XD commented on src/core/profiles/messages.ts
> +  'Contacto eliminado con exito';
```suggestion
  'Metodo de contacto eliminado con exito';
```

2023-12-10 11:45 UTC, Hector1567XD commented on src/core/profiles/profiles.controller.ts
> +  }
Definitivamente tienes que eliminar esto, te hiciste un CRUD cuando lo MENOS que buscaba era un CRUD
```suggestion
```

2023-12-10 11:45 UTC, Hector1567XD commented on src/core/profiles/service/index.ts
> +  }
Todo esto se va
```suggestion
```

2023-12-10 11:45 UTC, Hector1567XD commented on src/core/profiles/service/index.ts
> +  }
(Bueno, quiza no todo, pero lo vemos juntos despues de la daily)

2023-12-10 11:45 UTC, Hector1567XD commented on src/core/users/dto/update-user.dto.ts
>  export class UpdateUserDto extends PartialType(CreateUserDto) {
Deberia haber una forma de reutilizar todo lo de CreateUserDto pero haciendo los campos opcionales no?... podrias googlear o chatgptear algo de eso, seguro nos ahorramos MUCHO pero MUCHISIMO codigo

2023-12-10 11:45 UTC, Hector1567XD commented on src/core/users/entities/user.interface.ts
>  export interface UserI {
Le falta `document` no?

2023-12-10 11:45 UTC, Hector1567XD commented on src/core/users/entities/user.interface.ts
>  }
```suggestion
  email: string;
  document: string;
}
```
?

2023-12-10 21:01 UTC, HopeAero commented on src/core/users/entities/user.interface.ts
>  export interface UserI {
nop

2023-12-10 21:03 UTC, HopeAero commented on src/core/profiles/dto/responses.dto.ts
> +  skills: Skill[];
swagger se chispotea cuando una entidad tiene muchas relaciones y no puede hacer el ejem response asi que te recomienda hacer una clase para que la respuesta example funcione

2023-12-14 15:11 UTC, Yisustxz approved these changes
todo piola

2023-12-15 03:28 UTC, Nannajpg reviewed
/api/v1/profiles/my-profile/contact-methods esta rarongo

2023-12-17 00:35 UTC, HopeAero commented
> /api/v1/profiles/my-profile/contact-methods esta rarongo

correginho

2023-12-19 09:50 UTC, Hector1567XD commented on src/core/profiles/dto/responses.dto.ts
> +  skills: Skill[];
Tenemos que revisar esto juntos despues

2023-12-19 09:53 UTC, Hector1567XD requested changes

2023-12-19 09:53 UTC, Hector1567XD commented on src/core/profiles/dto/responses.dto.ts
> +export class ResponseMethodContactDTO {
Acabo de ver, esta es la respuesta cuando modificas los metodos de contacto del perfil, me parace genial devuelvas el Perfil con sus contact-methods actualizados en ese caso pero.... deberias reutilizar el DTO que ya hay para la respuesta de Perfil y llenarle los datos faltantes si hacen falta para cumplirlos

2023-12-19 09:53 UTC, Hector1567XD commented on src/core/profiles/dto/responses.dto.ts
> +export class ResponseMethodContactDTO {
Podrias reutilizar el servicio de profile para enviar respuesta

2023-12-20 15:45 UTC, luizzzito approved these changes
Los endpoints funcionan de forma correcta, y no creo que deban haber cambios en las respuestas

2023-12-22 02:42 UTC, LuisRivasW approved these changes

2023-12-29 03:32 UTC, Hector1567XD commented on src/core/profiles/dto/responses.dto.ts
> +}
Habria que borrarlo no ?

2023-12-29 03:34 UTC, Hector1567XD approved these changes

2023-12-29 05:15 UTC, merged