feature/idiomas
EquestriaReapers/LRT-Backend pull request #11
Opened 2023-12-08 14:37 UTC by HopeAero

Esta rama contiene feature/migration y hotfix/user-crud

### TESTING

api del backend para hacer las pruebas https://ucab-profile-backend.playoffside.online/api

Creedenciales para hacer las pruebas
`` {
  "email": "davidsalcedo388@gmail.com",
  "password": "123456"
}
``

Ruta de testeo

Primero crear un idioma
![imagen_2023-12-09_214215741](https://github.com/EquestriaReapers/LRT-Backend/assets/73862929/4062a9dd-6a5e-4d1c-a748-908a2e6b8600)

Segundo agregar idiomas o quitar idiomas del perfil logeado
![image](https://github.com/EquestriaReapers/LRT-Backend/assets/73862929/62e41577-e80c-418a-badf-fc3cd2c52a86)

Probar el get paginado para ver si la respuesta te gusto riki ki
![image](https://github.com/EquestriaReapers/LRT-Backend/assets/73862929/bf17c467-598b-47d6-a841-b420f71efca0)

Probar el get por id
![image](https://github.com/EquestriaReapers/LRT-Backend/assets/73862929/204dde4a-a9bb-4312-b9f8-701a35816a28)

2023-12-10 01:02 UTC, Hector1567XD requested changes
Quedo pendiente de hacer pruebas funcionales y revisar 2 archivos, necesitare ayuda para las pruebas funcionales, pls dejen instrucciones de testeo en el PR asi frontends tambien hacen dichas pruebas funcionales

2023-12-10 01:02 UTC, Hector1567XD commented on src/app.module.ts
> +import LanguageAction from './core/profiles/service/language.action';
Caballero, que es esto de `LenguagueAction` Xd, es `LenguagueService`, los `Services` son los que adentro tienen `Actions` y recordemos los `Action` son de **UN UNICO METODO** no exponen varios métodos publicos por que son para una unica funcion (pueden tener varios métodos privados, eso si).

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/auth/dto/register.dto.ts
> +  document: string;
What is document xD?

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/auth/dto/register.dto.ts
> +  @ApiProperty()
```suggestion
  @ApiProperty({  description: "Creo que aqui se podian poenr descripciones explicativas de cada vaina para no perderse no xD?" })
```

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/experience/entities/experience.entity.ts
> +
```suggestion

@ApiProperty()
```
Maybe?

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/experience/experience.controller.ts
> +  async removeMyExperiencia(
```suggestion
  async removeMyExperiencie(
```

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/experience/service/experience.service.ts
> +    }
Pienso que lo correcto es hacer una pre-validacion e.e
```suggestion
    const experience = await this.experienceRepository.findOne({ id });
    if (!experience) throw new NotFoundException(EXPERIENCE_NOT_FOUND);
    
    try {
        const experienceToRemove = await this.experienceRepository.softDelete({
           profileId: user.id,
           id: id,
        });

        if (experienceToRemove.affected === 0) {
           throw new InternalServerErrorException(UNKOWN_ERROR_DATABASE_MESSAGE);
        }
    } catch (error) {
       if (error instanceof InternalServerErrorException) throw error;
       throw new InternalServerErrorException(UNKOWN_ERROR_DATABASE_MESSAGE);
    }

```

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/experience/service/experience.service.ts
> +    }
Ademas, tambien nos permite hacer una validacion mas especializada
```suggestion
    const experience = await this.experienceRepository.findOne({ id });
    if (!experience) throw new NotFoundException(EXPERIENCE_NOT_FOUND);
    if (experience.profileId !== user.id) throw new ForbiddenException(YOU_NOT_HAVE_PERMISSION_MESSAGE);
    
    try {
        const experienceToRemove = await this.experienceRepository.softDelete({
           profileId: user.id,
           id: id,
        });
        if (experienceToRemove.affected === 0) {
           throw new InternalServerErrorException(UNKOWN_ERROR_DATABASE_MESSAGE);
        }
    } catch (error) {
       if (error instanceof InternalServerErrorException) throw error;
       throw new InternalServerErrorException(UNKOWN_ERROR_DATABASE_MESSAGE);
    }
```
PD: notese que uso `ForbiddenException` en lugar de `UnauthorizedException` ya que Unauthorized se usa cuando el usuario no esta autenticado ni tiene token, Forbidden es para cuando si bien esta autenticado, no tiene acceso a cierto recurso o cierto permiso

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/experience/service/experience.service.ts
> +    }
Me gustaria hicieran esto en este caso en concreto para tener algo de logica de negocio con prevalidaciones guardado por alli si llegamos a necesitarlo para un caso donde si o si necesitemos hacerlo de esta forma

Para el resto de casos donde simplemente se limitan a hacer `experienceToRemove.affected === 0` la verdad no lo se... diria que son deuda tecnica, pero no se si a partir de ahora sea bueno complicarse la vida haciendo esto o irrnos por lo simple (que no estoy seguro funcione en el 100% de los casos)

Queda de parte de la investigacion del manejo de errores en TypeORM que no se quien la esta haciendo

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/language/entities/language.entity.ts
> +  languageProfile: LanguageProfile[];
o.0...

Entiendo que esta es la relación con la PIVOTE de la ManyToMany, es decir la relación entre `Lenguage -> LenguageProfile -> Profile`

Pero... siempre que busquemos un lenguaje se traera el arreglo de TODOS los pivotes que tiene con TODOS los perfiles de la aplicacion? @HopeAero, preocupante

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/language/language.controller.spec.ts
> +  });
Esto no basta como prueba unitaria XD, supongo que aun estan por venir las verdaderas pruebas unitarias no?

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/language/language.controller.ts
> +  }
Este endpoint!

Deberiamos agregarle un parametro OPCIONAL que sea "name" y que puedas buscar un lenguaje por nombre para hacer el AUTOCOMPLETADO.

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/language/language.controller.ts
> +  }
Esto lo veo super requerido ✅

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/language/language.controller.ts
> +  }
Aunque... tambien se puede hacer un auto-completado en frontend... ya que de todas formas hay una cantidad finita de lenguajes en el mundo no e,e?.... idk, preguntemosle a Luis y a Anna

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/language/language.controller.ts
> +}
```suggestion
```
No se si sea un error de mi parte decir que no hagamos estos endpoints por que si, luego podemos lllegar a necesitarlos, pero...
1. Consumen espacio innecesario en el SWAGGER y en el codigo sabiendo que no los usaremos
2. Insitan a un supuesto admin panel que no tendremos todavia y se pierde tiempo haciendolos cuando realmente tenemos cosas mas importantes que hacer
3. Mejor hacer 3 endpoints que si vamos a usar, ponerle pruebas unitarias, mensajes personalizados, separarlos en distintas clases (actions) hacerlos bellacos a hacer el CRUD completo pero sin pruebas unitarias, sin mensajes personalizados, sin separacion en actions

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/language/language.controller.ts
> +}
La sugerencia dice que borremoslos, pero ya que estan hechos ps, ok, nos los borremos, pero la verdad no pienso que debemos seguir copiando y pegando endpoints de admin panel de forma mecanica, deberiamos centrarnos en los que realmente vamos a usar y hacerlos COMPLETOS (pruebas unitarias, encapsulamiento, etc)

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/language/language.controller.ts
> +  }
Tambien el problema con esto es que la APP usara un endpoint de ADMIN para poder obtener la lista de lenguajes, si no, por que le dariamos acceso al GRADUATE aqui?... pienso que es un error eso, la APP no deberia poder acceder a ningun endpoint de admin en lo posible

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/language/language.controller.ts
> +  }
⚠️ **Reitero, ya que estan hechos, no los borremos, pero porfavor, tengan eso en cuenta para proximos endpoints, no siempre hace falta completar el CRUD si no se va a usar**

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/language/language.module.ts
> +import { LanguageService } from './service/language.service';
~~Cual seria la diferencia entre el `LenguageService` y el `LenguageAction` e.e?~~

Ya vi la diferencia... el `LenguagueService` creo seria mas bien `LenguagueAdminService` mientras el otro seria `LenguagueService`, pero de hecho, mas correcto me pareceria que el `LenguagueService` se mantenga como `LenguagueService` y el `LenguagueAction` pase a llamarse `LenguagueProfileService`

Pero saben que seria incluso mas arrecho?, aplicar el `Facade Pattern`, se que lo viste en clases @LuisRivasW 7u7

Podriamos hacer un LenguagueServiceFacade, que dentro tendria metodos provenientes de LenguagueService y LenguagueProfileService, pero idk, la verdad no es tan necesario, igual lo ideal es que el LenguagueService sea un Facade en si mismo de los Actions, pero aja....

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/language/language.module.ts
> +import { LanguageService } from './service/language.service';
En resumen....
- LenguagueService -> LenguagueService (✅ Hecho)
- LenguagueAction -> LenguagueProfileService (✏️ Pendiente)

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/language/service/language.service.ts
> +      throw new NotFoundException(LANGUAGE_NOT_FOUND);
Mas bien no?, por que hubo un problema al crearlo
```suggestion
      throw new NotFoundException(ERROR_ON_DATABASE_MESSAGE);
```

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/language/service/language.service.ts
> +    return language;
Lo he comentado varias veces e.e
```suggestion
    return  await this.languageRepository.save(createLanguageDto);
```

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/profiles/dto/add-language.dto.ts
> +  level: string;
Deberia ser un ENUM y limitar el nivel a las opciones que le sistema permita, evaluar con @Nannajpg si usaremos A1, A2, B1, B2, etc... o mas bien "Basico" "Intermedio" "Avanzado" "Nativo" ,etc...
```suggestion
  level: string;
```

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/profiles/dto/add-language.dto.ts
> +  level: string;
PD: seria bueno hacer que sea nulo.

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/profiles/entities/language-profile.entity.ts
> +  level: string;
enum e.e

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/profiles/profiles.module.ts
> +  providers: [ProfilesService, FindAllPaginateAction, LanguageAction],
Ya hablamos sobre el nuevo nombre :B

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/profiles/service/index.ts
> +    return mappedProfile;
Esto se tiene que encapsular... todo el proceso de "Mapeo" de un perfil, en algun "Presenter" o "Adapter". investiguen sobre estos 2 tipos de clase, creo seria un `UserProfilePresenter` y deberia ir en la capa de presentacion incluso

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/profiles/service/language.action.ts
> +    return await this.languageProfileRepository.save(languageProfile);
Pls
```suggestion
    return await this.languageProfileRepository.save({
       languageId, profileId: profile.id, level
    });
```

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/profiles/service/language.action.ts
> +  async add(addLanguageProfile: AddLanguageDto, user: UserActiveInterface) {
Bonita logica de negocios @LuisRivasW, asi como tu UwU ❤️

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/profiles/service/language.action.ts
> +  async add(addLanguageProfile: AddLanguageDto, user: UserActiveInterface) {
Maybe, para evitar mal entendidos
```suggestion
  async add(addLanguageProfile: AddLanguageProfileDto, user: UserActiveInterface) {
```

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/profiles/service/language.action.ts
> +import { Injectable, NotFoundException } from '@nestjs/common';
Tengo pendiente de revisar este archivos despues, de momento enviare estos comentarios

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/users/service/users.service.ts
> +        'document',
Que es documenttttt 🙈

2023-12-10 01:02 UTC, Hector1567XD commented on src/core/profiles/service/profiles.queries.ts
>          FROM "profile_skills_skill" "profile_skills"
Quedo pendiente de revisar esta madre query

2023-12-10 01:14 UTC, HopeAero commented on src/core/auth/dto/register.dto.ts
> +  document: string;
cedula en ingles

2023-12-10 01:14 UTC, HopeAero commented on src/core/users/service/users.service.ts
> +        'document',
CEDULAAA manito

2023-12-10 01:15 UTC, HopeAero commented on src/core/profiles/service/profiles.queries.ts
>          FROM "profile_skills_skill" "profile_skills"
pero si esa madre query ya la revisaste en la hiper epic

2023-12-10 01:20 UTC, HopeAero commented on src/core/language/entities/language.entity.ts
> +  languageProfile: LanguageProfile[];
en realidad no lo hace xD si buscas los lenguajes solo te devuelve los lenguajes y ya los que esten registrados en la tabla lenguaje, los de la relacion LenguajeProfile solo es algo que se ve en los get de perfil que es para tener el campo level

2023-12-10 01:20 UTC, HopeAero commented on src/core/language/entities/language.entity.ts
> +  languageProfile: LanguageProfile[];
Se nota que no usaste el swagger cuando revisaste

2023-12-10 01:20 UTC, HopeAero commented on src/core/language/language.controller.spec.ts
> +  });
nop aun no vienen las pruebas pronto si

2023-12-10 01:23 UTC, HopeAero commented on src/core/language/language.controller.ts
> +  }
ese endpoint si debo darselo a la APP ellos tienen que registrar en un perfil con un select de los lenguajes existentes

2023-12-10 01:24 UTC, HopeAero commented on src/core/language/language.controller.ts
> +  }
solo le pongo el rol de Admin pq tambien puede usar ese endpoint el admin

2023-12-10 01:25 UTC, HopeAero commented on src/core/profiles/dto/add-language.dto.ts
> +  level: string;
Bueno esto lo tenemos que preguntar si quieres hacerlo un ENUM pq yo no se si los niveles A1, B1 se usan en todos los idiomas o solo en ingles

2023-12-10 01:39 UTC, HopeAero commented on src/core/profiles/entities/language-profile.entity.ts
> +  level: string;
bueno mande una estructura de como sera ese enum de los lvl

2023-12-10 01:45 UTC, HopeAero commented
> Quedo pendiente de hacer pruebas funcionales y revisar 2 archivos, necesitare ayuda para las pruebas funcionales, pls dejen instrucciones de testeo en el PR asi frontends tambien hacen dichas pruebas funcionales

ya te cree tu ruta de testeoo homo

2023-12-10 11:08 UTC, Hector1567XD commented on src/core/auth/dto/register.dto.ts
> +  document: string;
La verdad lo veo como un nombre bien poco descriptivo... pero no se como mas almacenarlo, maybe
```suggestion
  documentCi: string;
```
Si no se nos ocurre algo
```suggestion
  cedula: string; //xd
```
o
```suggestion
  citizenDocument: string;
```
Creo que la mejor seria
```suggestion
  documentNumber: string;
```

2023-12-10 11:08 UTC, Hector1567XD commented on src/core/auth/dto/register.dto.ts
> +  document: string;
documentNumber me voy mas por esa, pero investiguen a ver que se hace en esos casos

2023-12-10 11:08 UTC, Hector1567XD commented on src/core/auth/dto/register.dto.ts
> +  document: string;
o `identification`, idk

2023-12-10 11:09 UTC, Hector1567XD commented on src/core/auth/dto/register.dto.ts
> +  document: string;
En ese mismo orden de ideas, debemos hacer que este campo sea obligatorio, que se ponga en el registro y que además sea único, que te evite el registro si detecta a alguien mas con esa misma cédula

2023-12-10 11:18 UTC, Hector1567XD commented on src/core/experience/service/experience.service.ts
> +        throw new InternalServerErrorException(INTERNAL_SERVER_ERROR);
Bella lógica de negocios ❤.
Un último fix
```suggestion
      const experienceRemoved = await this.experienceRepository.softDelete({
        profileId: user.id,
        id: id,
      });
      if (experienceRemoved.affected === 0) {
        throw new InternalServerErrorException(INTERNAL_SERVER_ERROR);
```
Es una experiencia que ya se elimino, en tiempo pasado, no se va a eliminar

2023-12-10 11:18 UTC, Hector1567XD commented on src/core/language/language.controller.ts
> +  }
Si claro, se que va para las apps tambien, pero creeria que deberia estar en la etiqueta /lenguagues/ y no /admin-lenguagues/ pero si, el admin tambien lo necesita, yo haria 2 endpoints distintos aunque hagan lo mismo ps

Pero bueno, son complicaciones quiza innecesarias por ahora

2023-12-10 11:32 UTC, Hector1567XD commented on src/core/profiles/profiles.module.ts
> +import LanguagueProfileService from './service/languagueProfileService';
Creo que el estandar de nombres que seguimos es asi no?
```suggestion
import LanguagueProfileService from './service/languague-profile.service';
```

2023-12-10 11:32 UTC, Hector1567XD commented on src/core/profiles/service/profiles.queries.ts
> +      ) AS "languageProfile"
Servira si hago esto?
```suggestion
      ARRAY(
        SELECT DISTINCT ON (lgp.id) json_build_object(
          id, lgp.id,
          profileId, lgp.profileId,
          level, lgp.level,
          name, lg.name,
          languageId, lgp.languageId
        )::text
        FROM language_profile lgp
        JOIN language lg ON "lg.id=lgp.languageId
        WHERE lgp.profileId = profile.id
      ) AS languageProfile
```

2023-12-10 11:32 UTC, Hector1567XD commented on src/core/profiles/service/profiles.queries.ts
> +      ) AS "languageProfile"
Otra cosa, deberia ser languagues unicamente, no languagueProfile ya que si bien lo buscas en la pivote, el frontend sabe que esos son los lenguages del perfil ps... (amenos que le cambies el nombre luego en la capa de presentacion y no lo quieras cambiar aqui)

```suggestion
      ARRAY(
        SELECT DISTINCT ON ("language_profile"."id") json_build_object(
          'id', "language_profile"."id",
          'profileId', "language_profile"."profileId",
          'level', "language_profile"."level",
          'name', "languages"."name",
          'languageId', "language_profile"."languageId"
        )::text
        FROM "language_profile"
        JOIN "language" "languages" ON "languages"."id"="language_profile"."languageId"
        WHERE "language_profile"."profileId" = "profile"."id"
      ) AS languages // <------------------------------
```

2023-12-10 11:32 UTC, Hector1567XD commented on src/core/profiles/service/languagueProfileService.ts
> +      relations: ['languages'],
Para que seria esto?
```suggestion
```

2023-12-10 11:32 UTC, Hector1567XD commented on src/core/profiles/messages.ts
> +  'Perfil o idioma no se encontraron';
¿Por que Perfil o idioma? el perfil tiene otra validacion anterior con otro mensaje si no m equivoco
```suggestion
export const ERROR_LANGUAGUE_NOT_FOUND =
  'El idioma que intentas agregar al perfil no existe';
```

2023-12-10 11:32 UTC, Hector1567XD commented on src/core/profiles/service/languagueProfileService.ts
> +    }
ah ya... quiza sea bueno que sean 2 validaciones aparte

2023-12-10 11:33 UTC, Hector1567XD commented
Nuevamente no hice testing funcional, se lo delego a los frontends en ese aspecto :B

2023-12-10 16:04 UTC, HopeAero commented on src/core/profiles/service/profiles.queries.ts
> +      ) AS "languageProfile"
esta dudoso que eso funcione con el lgp.id xD, ya si cambiar el AS languages o cambiarlo en la presentacion de la respuesta ta bien

2023-12-15 03:39 UTC, Nannajpg approved these changes

2023-12-16 23:23 UTC, Yisustxz approved these changes
todo fino caballero 😎

2023-12-29 03:39 UTC, Hector1567XD commented on src/constants/enum/contact/contact.ts
> +  PHONE = 'phone',
Oriana habia quitado telefono? o estoy equivocado?
```suggestion
  WEBSITE = 'website',
```

2023-12-29 03:39 UTC, Hector1567XD commented on src/core/auth/service/auth.service.ts
> +      documentNumber,
Doble document Number??

2023-12-29 03:39 UTC, Hector1567XD commented on src/core/experience/entities/experience.entity.ts
> +
Papa esto no esta resuelto XD

2023-12-29 03:39 UTC, Hector1567XD commented on src/core/language/language.controller.ts
> +  }
@HopeAero

2023-12-29 03:39 UTC, Hector1567XD commented on src/core/language/language.controller.ts
> +  }
(Hagamoslo en otra tarea)

2023-12-29 03:39 UTC, Hector1567XD commented on src/core/language/language.controller.ts
> +  }
Se hara en https://github.com/EquestriaReapers/LRT-Backend/pull/14

2023-12-29 03:39 UTC, Hector1567XD approved these changes

2023-12-29 05:16 UTC, closed without merging