Feature/open search
EquestriaReapers/LRT-Backend pull request #15
Opened 2023-12-24 00:39 UTC by HopeAero

Mi orgullo el buscador que le hace competencia a Linkedin y google chrome UwU

2023-12-29 03:59 UTC, Hector1567XD commented on src/core/search/search.service.ts
> +          filter: filters,
```suggestion
          should,
          filter,
```

2023-12-30 19:10 UTC, Hector1567XD commented on src/core/search/search.controller.ts
> +  @ApiQuery({ name: 'countryResidence', required: false })
Aqui vamos a agregar un nuevo parametro para buscar, por que NO deberia ser un POST si no un GET

Pero.... hagamoslo en otra tarea u en otro sitio, no tenemos mucho tiempo justo ahora

2023-12-30 19:10 UTC, Hector1567XD commented on src/core/search/search.controller.ts
> +    page = Number(page) || 1;
Maybe? para evitar que sea 0 la pagina
```suggestion
    page = Number(page) || 1;
    if (page === 0) page = 1;
```

2023-12-30 19:10 UTC, Hector1567XD commented on src/core/search/search.module.ts
> +      node: 'https://localhost:9200',
.env ??

2023-12-30 20:08 UTC, HopeAero commented on src/core/search/search.controller.ts
> +  @ApiQuery({ name: 'countryResidence', required: false })
entendido

2023-12-30 20:13 UTC, Hector1567XD requested changes

2023-12-30 20:13 UTC, Hector1567XD commented on src/core/search/search.service.ts
> +  }
```suggestion
  private async getValidatedCarreras(_carrerasRaw: any) {
    if (_carrerasRaw) {
      const carrerasRaw = Array.isArray(_carrerasRaw) ? _carreras : [_carrerasRaw];

      return carrerasRaw.map((carreraRaw: string) => {
        const carreraLower = carreraRaw.toLowerCase() as Career;

        if (!Object.values(Career).includes(carreraLower)) {
          throw new BadRequestException(
            `Valor inválido para carrera: ${carreraLower}`,
          );
        }

        return carreraLower;
      });
    }

    return null;
  }
```

2023-12-30 20:13 UTC, Hector1567XD commented on src/core/search/search.service.ts
> +      career = await this.validateCarrera(career);
```suggestion
      career = await this.getValidatedCarreras(career);
```

2023-12-30 20:13 UTC, Hector1567XD commented on src/core/search/search.service.ts
> +  private async validateCarrera(carrera: any) {
Por que chuchas el ASYNC XD???
```suggestion
  private validateCarrera(carrera: any) {
```

2023-12-30 20:13 UTC, Hector1567XD commented on src/core/search/search.service.ts
> +  private async formatedData(data: any) {
Por que chuchas el ASYNC XD???
```suggestion
  private formatedData(data: any) {
```

2023-12-30 20:13 UTC, Hector1567XD commented on src/core/search/search.service.ts
> +    return respuestaNormal;
```suggestion
    return data.map((item) => ({
      ...item,
      user: {
        id: item.id,
        name: item.name,
        lastname: item.lastname,
        email: item.email,
      },
    }));
```

2023-12-30 20:13 UTC, Hector1567XD commented on src/core/search/search.service.ts
> +      data = await this.formatedData(data);
```suggestion
      data = this.formatedData(data);
```

2023-12-30 20:13 UTC, Hector1567XD commented on src/core/search/search.service.ts
> +  }
Esto hagamoslo en un Action diferente, totalmente diferente XD

2023-12-30 20:13 UTC, Hector1567XD commented on src/core/search/search.service.ts
> +  }
Osea mismo servicio, pero en un action diferente

2023-12-30 20:13 UTC, Hector1567XD commented on src/core/search/search.service.ts
> +  }
Un Subservicio otra clase ps

2023-12-30 20:13 UTC, Hector1567XD commented on src/core/search/search.service.ts
> +      if (career && Array.isArray(career)) {
```suggestion
      if (career) {
```
Hace falta validar si es un arreglo? `validateCarrera` no lo hace ya?

2023-12-30 20:13 UTC, Hector1567XD commented on src/core/search/search.service.ts
> +              mainTitle: c,
```suggestion
        career.forEach((mainTitle) => {
          filters.push({
            match: {
              mainTitle
```

2023-12-30 20:13 UTC, Hector1567XD commented on src/core/search/search.service.ts
> +              countryResidence: country,
```suggestion
        countriesResidence.forEach((countryResidence) => {
          filters.push({
            match: {
              countryResidence,
```

2023-12-30 21:06 UTC, HopeAero commented on src/core/search/search.service.ts
> +      if (career && Array.isArray(career)) {
mmmmm creo que tienes razon pero deberia probar por algo lo puse y no recuerdo si era pq me lo devolvia como un string

2023-12-30 23:19 UTC, Hector1567XD approved these changes

2023-12-31 03:41 UTC, merged