Feature/education
EquestriaReapers/LRT-Backend pull request #16
Opened 2023-12-29 02:42 UTC by HopeAero

la definicion de sexo

2023-12-30 20:01 UTC, Hector1567XD requested changes
Exceso de sexo caballero, pero hagame los fixesinhos

2023-12-30 20:01 UTC, Hector1567XD commented on src/core/education/service/education.service.ts
> +    });
Debe estar quemado que toda experiencia que puedas crear NO es de la UCAB
```suggestion
      profileId: user.id,
      isUCAB: false
    });
```

2023-12-30 20:01 UTC, Hector1567XD commented on src/core/education/service/education.service.ts
> +        updateEducationDto.principal === false)
![image](https://github.com/EquestriaReapers/LRT-Backend/assets/22270579/b8cebf08-b106-4f53-bbd8-a89f3a4232b1)

Papa xd `q || !q = true`

```suggestion
      validateEducationIsUCAB.isUCAB === true
```

2023-12-30 20:01 UTC, Hector1567XD commented on src/core/education/service/education.service.ts
> +        updateEducationDto.principal === false)
Por cierto, no hace falta el === true si es que es true

```suggestion
      validateEducationIsUCAB.isUCAB
```

2023-12-30 20:01 UTC, Hector1567XD commented on src/core/education/service/education.service.ts
> +      education = await this.educationRepository.update(
```suggestion
    } else {
      education = await this.educationRepository.update(
```

2023-12-30 20:01 UTC, Hector1567XD commented on src/core/education/service/education.service.ts
> +        },
Quemar que no puedes modificar el isUcab
```suggestion
          ...updateEducationDto,
          isUCAB: false
        },
```

2023-12-30 20:01 UTC, Hector1567XD commented on src/core/education/service/education.service.ts
> +    const validateEducationIsUCAB = await this.educationRepository.findOne({
```suggestion
    const currentEducationState = await this.educationRepository.findOne({
```
o
```suggestion
    const currentEducation = await this.educationRepository.findOne({
```

2023-12-30 20:01 UTC, Hector1567XD commented on src/core/education/service/education.service.ts
> +        id: id,
```suggestion
        id,
```

2023-12-30 20:01 UTC, Hector1567XD commented on src/core/education/service/education.service.ts
> +    const verifyEducationUCAB = await this.educationRepository.findOne({
```suggestion
    const currentEducation = await this.educationRepository.findOne({
```

2023-12-30 20:01 UTC, Hector1567XD commented on src/core/education/service/education.service.ts
> +    if (verifyEducationUCAB.isUCAB === true) {
```suggestion
    if (currentEducation.isUCAB) {
```

2023-12-31 00:51 UTC, HopeAero commented on src/core/education/service/education.service.ts
> +        updateEducationDto.principal === false)
Comentasinho no es un if para que solo sea vdd es para verificar que no entre un undefined

2023-12-31 00:53 UTC, HopeAero commented on src/core/education/service/education.service.ts
> +      education = await this.educationRepository.update(
Igual que el de arriba correginho

2023-12-31 01:27 UTC, LuisRivasW approved these changes

2023-12-31 03:17 UTC, Hector1567XD approved these changes

2023-12-31 03:42 UTC, merged