Endpoints de ubicacion
EquestriaReapers/LRT-Backend pull request #19
Opened 2023-12-30 19:12 UTC by HopeAero

2023-12-30 20:15 UTC, Hector1567XD requested changes

2023-12-30 20:15 UTC, Hector1567XD commented on src/core/location/service/location.service.ts
> +  async findAll(name?: string) {
Recomiendo poner como diablos es la respuesta :B
```suggestion
  async findAll(name?: string): Promise<Location> {
```

2023-12-30 20:15 UTC, Hector1567XD commented on src/core/location/location.controller.ts
> +  findAll(@Query('name') name: string) {
De hecho la necesitamos especialmetne aqui para qu salga en swagger

2023-12-30 22:14 UTC, GreenieWarren approved these changes
Ya probé la locación, está de perlas papa, gracias por esta api ñam lam

2023-12-31 03:18 UTC, Hector1567XD approved these changes

2023-12-31 03:18 UTC, Hector1567XD commented on src/core/location/location.controller.ts
> +import { LocationResponse } from './dto/response.dto';
Basta con Location, no con LocationResponse XD, pero x
```suggestion
import { Location } from './dto/response.dto';
```

2023-12-31 03:44 UTC, merged